//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Contact_Manage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public int PersonId { get; set; }

        [Display(Name = "First Name")]
        [Required]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }

        [Display(Name = "Last Name")]
        [Required]
        public string LastName { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Of Birth")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }

        public System.DateTime AddedOn { get; set; }

        public string AddedBy { get; set; }
        [Display(Name = "Home Address")]
        public string HomeAddress { get; set; }

        [Display(Name = "Home City")]
        [Required]
        public string HomeCity { get; set; }

        [Display(Name = "Facebook Account")]
        [Url]
        public string FaceBookAccountId { get; set; }

        [Display(Name = "LinkedIn Account")]
        [Url]
        public string LinkedInId { get; set; }


        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string ImagePath { get; set; }

        [Display(Name = "Twitter Account")]
        [Url]
        public string TwitterId { get; set; }

        [Display(Name = "Email")]
        [EmailAddress]
        [Required]
        public string EmailId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
